name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  General:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello, world!
        run: echo Hello, world!
  CodeStyle:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2  
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
